advantage_point:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: advantage-point-465313
      dataset: advpoint__dbt
      threads: 8
      location: US
      job_execution_timeout_seconds: 1800
