advantage_point:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: advantage-point-465313
      dataset: advpoint__dbt
      threads: 8
      location: US
      job_execution_timeout_seconds: 1800

advantage_point_dbt_docs_ci:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: advantage-point-465313
      dataset: advpoint__dbt
      keyfile_json: "{{ env_var('SA_ADVPOINT_PROD_DBT_KEY') }}"
      threads: 8
      location: US
      job_execution_timeout_seconds: 1800
