advantage_point:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: advantage-point-465313
      dataset: advpoint__dbt
      threads: 4
      location: US
      job_execution_timeout_seconds: 300
